const Settings = {

	//PADDLE
	PADDLE_W : 100,
	PADDLE_H : 30,
	PADDLE_PADDING_BOTTOM: 50,
	PADDLE_COLOR : '#ff972c',
	//BALLS
	BALL_W : 15,
	BALL_H : 15,
	BALL_VELOCITY : 5,
	BALL_MIN_VELOCITY : 1,
	BALL_MAX_VELOCITY : 20,
	BALL_COLOR : '#fff93a',
	//BLOCKS
	BLOCK_W : 55,
	BLOCK_H : 20,
	BLOCK_COLOR : '#842727',
	//BORDERs
	BORDER_W : 0,
	BORDER_COLOR : '#842727',
	//BACKGROUND
	BACKGROUND_COLOR : '#000',
	//EFFECTS
	EFFECT_PADDLE_STRETCH : true,
	EFFECT_BORDER_BOUNCE : true,
	EFFECT_BALL_STRETCH : true,
	EFFECT_BALL_ROTATION : true,
	EFFECT_BLOCK_RESET_ANIMATION : true,
	EFFECT_BALL_COLLIDE_SCALE : true,
	EFFECT_BALL_COLLIDE_COLOR : true
}