const settings = {

	//PADDLE
	PADDLE_W : 100,
	PADDLE_H : 30,
	PADDLE_PADDING_BOTTOM: 50,
	PADDLE_COLOR : '#FFF',
	//BALLS
	BALL_W : 15,
	BALL_H : 15,
	BALL_VELOCITY : 5,
	BALL_VELOCITY_MIN : 10,
	BALL_VELOCITY_MAX : 50,
	BALL_COLOR : '#FFF',
	//BLOCKS
	BLOCK_W : 55,
	BLOCK_H : 20,
	BLOCK_COLOR : '#FFF',
	//BORDERs
	BORDER_W : 0,
	//BACKGROUND
	BACKGROUND_COLOR : '#000',
	//EFFECTS
	EFFECT_PADDLE_STRETCH : true,
}